<div class="footer">
    <div class="footer-body">
        <div class="footer-items">
            <div class="items-list">
                <div class="items-left">
                    <p class="items-title lang-aboutTitle">关于VNBIG</p>
                    <ul class="items">
                        <!-- <li><a href="{{path}}" class="lang-contact">联系我们</a></li> -->
                        <!--<li><a href="{{path}}help-expense.html" class="lang-fee">费用</a></li>-->
                        <!-- <li><a href="{{path}}" class="lang-privacy">隐私政策</a></li> -->
                        <li><a href="{{path}}agreement.html" class="lang-agreement">使用条款</a></li>
	                    <!-- <li><a href="{{path}}Question.aspx" class="lang-worksheet">在线工单</a></li> -->
                    </ul>
                </div>
            </div>
            <!-- <div class="items-list">
                <div class="items-center">
                    <p class="items-title lang-portTitle">支持</p>
                    <ul class="items">
                        <li><a href="{{path}}help-contact.html" class="lang-contactPort">联系我们</a></li>
                        <li><a href="{{path}}" class="lang-portRes">支持资源</a></li>
                        <li><a href="{{path}}" class="lang-toWap">切换到手机网站</a></li>
                    </ul>
                </div>
            </div> -->
            <div class="items-list">
                <div class="items-right">
                    <p class="items-title lang-footerNewsTitle">新闻</p>
                    <ul class="items">
                        <li><a href="{{path}}help-news.html" class="lang-newsText">新闻稿</a></li>
                        <!-- <li><a href="{{path}}" class="lang-twitter">推特</a></li> -->
                    </ul>
                </div>
            </div>
        </div>
        <div class="some-else">
            <p class="footer-prompt lang-warning">---</p>
            <p class="footer-info lang-copyright">-</p>
        </div>
    </div>
</div>