<div class="help-block">
    <p class="section-title lang-rightTitle" index="0">联系支持</p>
    <p class="section-text lang-rightText" index="0">所有技术支持问题都通过我们的支持系统来处理。</p>
</div>
<div class="help-block">
    <p class="section-title lang-rightTitle" index="1">新闻</p>
    <a class="section-text lang-rightNews" href="{{path}}help-news.html">新闻稿</a>
    <div class="section-middle"></div>
    <span class="section-text lang-rightTwitter" >推特</span>
</div>
<div class="help-block">
    <p class="section-title lang-rightTitle" index="2">社交媒体</p>
    <p class="section-text lang-rightText" index="1">想知道VNBIG发生了什么？关注我们。</p>
</div>