<!-- build:js ./Web/js/lang.min.js -->
<script src="./Web/js/config.js"></script>
<script src="./Web/js/common/lang-zh.js"></script>
<script src="./Web/js/common/lang-vi.js"></script>
<script src="./Web/js/common/lang-en.js"></script>
<script src="./Web/js/common/lang-ct.js"></script>
<!-- endbuild -->
<!-- build:js ./Web/js/common.min.js -->
<script src="./Web/js/plugins/jquery.min.js"></script>
<script src="./Web/js/plugins/big.js"></script>
<script src="./Web/js/common/util.js"></script>
<script src="./Web/js/common/common.js"></script>
<script src="./Web/js/common/set-lang.js"></script>
<script src="./Web/js/common/dialog.js"></script>
<script src="./Web/js/common/loading.js"></script>
<script src="./Web/js/common/header.js"></script>
<script src="./Web/js/common/get-userinfo.js"></script>
<script src="./Web/js/common/struct.js"></script>
<script src="./Web/js/common/page.turn.js"></script>
<!-- endbuild -->
