<div class="market-box no-border table-box market-hide text-center" id="coinList">
    <div class="list thead line-2">
        <span class="td td-20 lang-dealListItems" index="0">---</span>
        <span class="td td-30">
            <span class="text">
                <span class="lang-dealListItems" index="1">---</span>
                ( <span class="coin-from">--</span> )
            </span>
        </span>
        <span class="td td-25 lang-dealListItems" index="2">---</span>
        <span class="td td-25 lang-dealListItems" index="3">---</span>
    </div>
    <ul class="tbody">
        <!--<li class="list click">-->
        <!--<span class="td td-20">ETH</span>-->
        <!--<span class="td td-30">0.07302143</span>-->
        <!--<span class="td td-25">316331633163</span>-->
        <!--<span class="td td-25 rise">+0.83</span>-->
        <!--</li>-->
    </ul>
</div>

